apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-argo-application
  # namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/leozw/argocd-gitops
    targetRevision: HEAD
    path: node-sonar-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: node-sonar-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true